/* Durable drafts for a small set of low-risk mutations. The server remains authoritative. */
const DB_NAME='araia-workspace-offline-v4';
const SAFE_ACTIONS=new Set(['task.update','timesheet.create','lead.create','activity.create','mom.create','work.create','work.submit','work.complete','attendance.checkIn','attendance.checkOut']);
function database(){return new Promise((resolve,reject)=>{const open=indexedDB.open(DB_NAME,1);open.onupgradeneeded=()=>{const db=open.result;db.createObjectStore('queue',{keyPath:'id'});db.createObjectStore('snapshots',{keyPath:'user_id'});};open.onsuccess=()=>resolve(open.result);open.onerror=()=>reject(open.error);});}
async function transact(store,mode,fn){const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode),result=fn(tx.objectStore(store));tx.oncomplete=()=>{db.close();resolve(result?.result);};tx.onerror=()=>{db.close();reject(tx.error);};});}
export function canQueue(action,payload){return SAFE_ACTIONS.has(action)&&!(action==='attendance.checkIn'&&payload.source!=='OFFICE');}
export async function enqueue(userId,action,payload){if(!userId||!canQueue(action,payload))throw Error('Aksi ini memerlukan koneksi internet.');const row={id:payload.requestId,user_id:userId,action,payload,created_at:new Date().toISOString(),status:'Menunggu',error:''};await transact('queue','readwrite',store=>store.add(row));return row;}
export async function listQueue(userId){const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('queue','readonly'),req=tx.objectStore('queue').getAll();req.onsuccess=()=>{db.close();resolve(req.result.filter(x=>x.user_id===userId).sort((a,b)=>a.created_at.localeCompare(b.created_at)));};req.onerror=()=>{db.close();reject(req.error);};});}
export async function markQueue(row,status,error=''){await transact('queue','readwrite',store=>store.put({...row,status,error:String(error).slice(0,300)}));}
export async function removeQueue(id){await transact('queue','readwrite',store=>store.delete(id));}
const SNAPSHOT_KEYS=['projects','tasks','attendance','employees','leads','clients','opportunities','inventory','work_items'];
export async function saveSnapshot(data){if(!data?.user?.id)return;const safe={user_id:data.user.id,user:data.user,saved_at:new Date().toISOString()};for(const key of SNAPSHOT_KEYS)safe[key]=data[key]||[];safe.projects=safe.projects.map(x=>({id:x.id,name:x.name,business_unit_id:x.business_unit_id,stage:x.stage}));safe.tasks=safe.tasks.map(x=>({id:x.id,project_id:x.project_id,title:x.title,assignee_user_id:x.assignee_user_id,due_date:x.due_date,status:x.status}));safe.attendance=safe.attendance.map(x=>({id:x.id,user_id:x.user_id,check_in_at:x.check_in_at,check_out_at:x.check_out_at,source:x.source,status:x.status}));safe.leads=safe.leads.map(x=>({id:x.id,company_name:x.company_name,business_unit_id:x.business_unit_id}));safe.clients=safe.clients.map(x=>({id:x.id,company_name:x.company_name,business_unit_id:x.business_unit_id}));safe.opportunities=safe.opportunities.map(x=>({id:x.id,name:x.name,business_unit_id:x.business_unit_id}));safe.inventory=safe.inventory.map(x=>({id:x.id,sku:x.sku,item_name:x.item_name,location:x.location,unit:x.unit,business_unit_id:x.business_unit_id}));safe.employees=safe.employees.map(x=>({id:x.id,user_id:x.user_id,name:x.name,role:x.role,business_unit_id:x.business_unit_id,status:x.status}));safe.work_items=safe.work_items.filter(x=>!['grievance','discipline','employee_contract','benefit','payable','receivable','tax_register'].includes(x.type)).map(x=>({id:x.id,type:x.type,title:x.title,business_unit_id:x.business_unit_id,status:x.status,owner_user_id:x.owner_user_id,assignee_user_id:x.assignee_user_id,version:x.version,updated_at:x.updated_at,details:{}}));await transact('snapshots','readwrite',store=>store.put(safe));}
export async function loadSnapshot(userId){const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('snapshots','readonly'),req=tx.objectStore('snapshots').get(userId);req.onsuccess=()=>{db.close();resolve(req.result||null);};req.onerror=()=>{db.close();reject(req.error);};});}
