import assert from 'node:assert/strict';

const listeners={};
const values=new Map();
const app={innerHTML:'',addEventListener(name,fn){listeners[name]=fn;},querySelector(){return null;}};
const toast={textContent:'',classList:{add(){},remove(){}}};
globalThis.document={getElementById(id){return id==='app'?app:toast;}};
globalThis.localStorage={getItem:key=>values.get(key)||null,setItem:(key,val)=>values.set(key,val),removeItem:key=>values.delete(key)};
globalThis.sessionStorage={getItem:()=>null,setItem(){},removeItem(){}};
Object.defineProperty(globalThis,'navigator',{value:{onLine:true},configurable:true});
globalThis.window={addEventListener(){},scrollTo(){}};
globalThis.setInterval=()=>0;
await import('../frontend/app.js');
assert.match(app.innerHTML,/araia-logo-white\.png/);
assert.match(app.innerHTML,/id="login-form"/);
assert.match(app.innerHTML,/Nama pengguna/);
assert.doesNotMatch(app.innerHTML,/Google Sign-In|google-login/);
assert.match(app.innerHTML,/Coba tampilan/);
const click=action=>listeners.click({target:{closest(selector){return selector==='[data-action]'?{dataset:{action},classList:{contains:()=>false}}:null;}}});
const clickData=(key,value,more={})=>listeners.click({target:{closest(selector){return selector===`[data-${key}]`?{dataset:{[key.replace(/-([a-z])/g,(_,letter)=>letter.toUpperCase())]:value,...more},classList:{contains:()=>false}}:null;}}});
await click('demo-login');
assert.match(app.innerHTML,/Halo, Mimo/);
assert.match(app.innerHTML,/DOTSIXTWOO/);
assert.doesNotMatch(app.innerHTML,/data-page="inventory"/,'PM should not see warehouse menu');
await click('more-menu');
assert.match(app.innerHTML,/Coba peran lain/);
listeners.change({target:{id:'roleSelect',value:'LOGISTICS'}});
assert.match(app.innerHTML,/data-page="inventory"/,'Logistics should see warehouse');
assert.doesNotMatch(app.innerHTML,/data-page="leads"/,'Logistics should not see CRM');
listeners.change({target:{id:'roleSelect',value:'PM'}});
await clickData('page','money');
assert.match(app.innerHTML,/Keuangan & pengadaan/);
await clickData('subtab','expenses');
assert.match(app.innerHTML,/Ajukan biaya proyek/);
await clickData('modal','expense');
assert.match(app.innerHTML,/id="entry-form"/);
globalThis.FormData=class {constructor(form){this.fields=Object.entries(form.fields);}*[Symbol.iterator](){yield* this.fields;}};
const submitButton={disabled:false,textContent:'Simpan'};
await listeners.submit({target:{id:'entry-form',dataset:{kind:'expense',id:''},fields:{project_id:'P-101',category:'Produksi',description:'Backdrop',amount:'150000'},querySelector:()=>submitButton},preventDefault(){}});
let data=JSON.parse(values.get('araia-demo-data'));
assert.equal(data.expenses[0].status,'Menunggu');
assert.equal(data.approvals[0].type,'PROJECT_EXPENSE');
await click('more-menu');
listeners.change({target:{id:'roleSelect',value:'FINANCE_DIRECTOR'}});
await clickData('page','approvals');
assert.match(app.innerHTML,/Setujui/);
await clickData('action','approve',{id:data.approvals[0].id});
data=JSON.parse(values.get('araia-demo-data'));
assert.equal(data.expenses[0].status,'Disetujui');
listeners.change({target:{id:'roleSelect',value:'PM'}});
await clickData('page','sales');
assert.match(app.innerHTML,/Buat pesanan/);
await clickData('modal','sale');
assert.match(app.innerHTML,/Harga jual per unit/);
const line={querySelector(selector){return {value:selector.includes('sku')?'KTD-PEACH':selector.includes('quantity')?'5':'20000'};}};
await listeners.submit({target:{id:'entry-form',dataset:{kind:'sale',id:''},fields:{project_id:'P-101',client_id:'C-1',location:'Gudang Utama',sku:'KTD-PEACH',quantity:'5',unit_price:'20000'},querySelector:()=>submitButton,querySelectorAll:()=>[line]},preventDefault(){}});
data=JSON.parse(values.get('araia-demo-data'));
assert.equal(data.sales[0].total,100000);
assert.equal(data.inventory[0].quantity,340,'creating order does not deduct stock');
listeners.change({target:{id:'roleSelect',value:'LOGISTICS'}});
await clickData('page','sales');
assert.match(app.innerHTML,/Penuhi pesanan/);
await clickData('action','fulfill-sale',{id:data.sales[0].id});
data=JSON.parse(values.get('araia-demo-data'));
assert.equal(data.inventory[0].quantity,335);
assert.equal(data.movements[0].reference_id,data.sales[0].id);
await clickData('page','inventory');
assert.match(app.innerHTML,/Catat opname/);
await clickData('modal','stockCount');
await listeners.submit({target:{id:'entry-form',dataset:{kind:'stockCount',id:''},fields:{inventory_id:'I-1',counted_quantity:'330',reason:'Hitung fisik'},querySelector:()=>submitButton},preventDefault(){}});
data=JSON.parse(values.get('araia-demo-data'));
assert.equal(data.inventory[0].quantity,335);
assert.equal(data.stock_counts[0].status,'Menunggu persetujuan');
listeners.change({target:{id:'roleSelect',value:'GA_SUPERVISOR'}});
await clickData('page','approvals');
await clickData('action','approve',{id:data.stock_counts[0].approval_id});
data=JSON.parse(values.get('araia-demo-data'));
assert.equal(data.inventory[0].quantity,330);
assert.equal(data.stock_counts[0].status,'Disesuaikan');
listeners.change({target:{id:'roleSelect',value:'FINANCE_DIRECTOR'}});
await clickData('page','money');
await clickData('subtab','invoices');
assert.match(app.innerHTML,/Buat tagihan/);
await clickData('modal','invoice');
await listeners.submit({target:{id:'entry-form',dataset:{kind:'invoice',id:''},fields:{sale_order_id:data.sales[0].id,due_date:'2026-12-31'},querySelector:()=>submitButton},preventDefault(){}});
data=JSON.parse(values.get('araia-demo-data'));
assert.equal(data.invoices[0].amount,100000);
await clickData('subtab','invoices');
await clickData('modal','payment');
await listeners.submit({target:{id:'entry-form',dataset:{kind:'payment',id:''},fields:{invoice_id:data.invoices[0].id,amount:'100000',method:'Transfer',reference:'TRX-1',paid_at:'2026-09-27'},querySelector:()=>submitButton},preventDefault(){}});
data=JSON.parse(values.get('araia-demo-data'));
assert.equal(data.invoices[0].status,'Lunas');
assert.equal(data.payments.length,1);
listeners.change({target:{id:'roleSelect',value:'PM'}});
await clickData('page','money');
await clickData('subtab','purchases');
await clickData('modal','purchase');
await listeners.submit({target:{id:'entry-form',dataset:{kind:'purchase',id:''},fields:{project_id:'P-101',vendor_id:'V-1',title:'Stok Peach Tea',sku:'KTD-PEACH',quantity:'3',unit_cost:'10000'},querySelector:()=>submitButton},preventDefault(){}});
data=JSON.parse(values.get('araia-demo-data'));
const pr=data.purchases[0];
listeners.change({target:{id:'roleSelect',value:'FINANCE_DIRECTOR'}});
await clickData('page','approvals');
await clickData('action','approve',{id:pr.approval_id});
listeners.change({target:{id:'roleSelect',value:'GA_SUPERVISOR'}});
await clickData('page','money');
await clickData('subtab','purchases');
await clickData('action','issue-order',{id:pr.id});
data=JSON.parse(values.get('araia-demo-data'));
const po=data.orders[0];
await clickData('action','issue-po',{id:po.id});
await clickData('modal',`receiveOrder:${po.id}`);
await listeners.submit({target:{id:'entry-form',dataset:{kind:'receiveOrder',id:po.id},fields:{location:'Gudang Utama'},querySelector:()=>submitButton},preventDefault(){}});
data=JSON.parse(values.get('araia-demo-data'));
assert.equal(data.orders[0].status,'Diterima');
assert.equal(data.inventory[0].quantity,333);
listeners.change({target:{id:'roleSelect',value:'PM'}});
await clickData('page','tasks');
await clickData('modal','task');
await listeners.submit({target:{id:'entry-form',dataset:{kind:'task',id:''},fields:{title:'Periksa booth',project_id:'P-101',assignee_user_id:'staff-1',due_date:'2026-10-01'},querySelector:()=>submitButton},preventDefault(){}});
data=JSON.parse(values.get('araia-demo-data'));
const assigned=data.tasks[0];
assert.equal(assigned.assignee_user_id,'staff-1');
listeners.change({target:{id:'roleSelect',value:'TALENT_PROJECT'}});
await clickData('page','tasks');
assert.match(app.innerHTML,/Periksa booth/);
await clickData('action','start-task',{id:assigned.id});
await clickData('action','finish-task',{id:assigned.id});
data=JSON.parse(values.get('araia-demo-data'));
assert.equal(data.tasks[0].status,'Selesai');
listeners.change({target:{id:'roleSelect',value:'PM'}});
await clickData('page','projects');
assert.match(app.innerHTML,/Tugas selesai/);
await clickData('page','work');
await clickData('work-area','ERP');
await clickData('work-type','budget_plan');
assert.match(app.innerHTML,/Rencana anggaran proyek/);
await clickData('modal','workCreate:budget_plan');
await listeners.submit({target:{id:'entry-form',dataset:{kind:'workCreate',type:'budget_plan',id:''},fields:{title:'Anggaran booth',business_unit_id:'DOTSIXTWOO',subject:'PROJECT|P-101',assignee_user_id:'demo','detail:amount':'100000','detail:category':'Produksi','detail:due_date':'2026-10-30','detail:summary':'Perlu pengesahan Finance'},querySelector:()=>submitButton},preventDefault(){}});
data=JSON.parse(values.get('araia-demo-data'));
const work=data.work_items[0];assert.equal(work.status,'Draft');
await clickData('work-action','submit',{id:work.id});
data=JSON.parse(values.get('araia-demo-data'));assert.equal(data.work_items[0].status,'Menunggu persetujuan');
listeners.change({target:{id:'roleSelect',value:'FINANCE_DIRECTOR'}});
await clickData('page','approvals');
await clickData('action','approve',{id:data.work_items[0].approval_id});
data=JSON.parse(values.get('araia-demo-data'));assert.equal(data.work_items[0].status,'Disetujui');
await clickData('page','money');await clickData('subtab','ledger');await clickData('modal','journal');
const journalLines=[['1000','50000','0'],['4000','0','50000']].map(([account,debit,credit])=>({querySelector(selector){return {value:selector.includes('account_code')?account:selector.includes('debit')?debit:credit};}}));
await listeners.submit({target:{id:'entry-form',dataset:{kind:'journal',id:''},fields:{business_unit_id:'DOTSIXTWOO',entry_date:'2026-09-27',reference:'BANK-UI-1',description:'Penerimaan jasa'},querySelector:()=>submitButton,querySelectorAll:()=>journalLines},preventDefault(){}});
data=JSON.parse(values.get('araia-demo-data'));assert.equal(data.journals[0].status,'Draft');
await clickData('action','journal-submit',{id:data.journals[0].id});
data=JSON.parse(values.get('araia-demo-data'));
listeners.change({target:{id:'roleSelect',value:'CEO'}});
await clickData('page','approvals');await clickData('action','approve',{id:data.journals[0].approval_id});
data=JSON.parse(values.get('araia-demo-data'));assert.equal(data.journals[0].status,'Posted');
await clickData('page','catalog');assert.match(app.innerHTML,/Semua kebutuhan/);
assert.match(app.innerHTML,/HRIS-01/);
console.log('Frontend smoke tests passed: roles, approvals, sales, stock, billing, PO, tasks, workflow, balanced journal, catalog.');
