"""Generate identical workflow definitions for the PWA and Apps Script."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIELDS = {
    'candidate_name': ('Nama kandidat', 'text'), 'person_name': ('Nama orang / pihak', 'text'),
    'role_name': ('Peran / jabatan', 'text'), 'start_date': ('Tanggal mulai', 'date'),
    'end_date': ('Tanggal selesai', 'date'), 'due_date': ('Batas waktu', 'date'),
    'summary': ('Catatan dan langkah berikutnya', 'textarea'), 'amount': ('Nilai (Rp)', 'number'),
    'quantity': ('Jumlah', 'integer'), 'rating': ('Penilaian 1–5', 'rating'),
    'target': ('Target', 'text'), 'category': ('Kategori', 'text'),
    'course': ('Nama pelatihan', 'text'), 'reference': ('Nomor referensi', 'text'),
    'hours': ('Jam', 'number'), 'location': ('Lokasi', 'text'),
    'contact_email': ('Email kontak', 'email'),
}
catalog = []
for line in (ROOT / 'catalog/workflow-source.tsv').read_text().splitlines():
    if not line or line.startswith('#'):
        continue
    key, area, label, audience, approver, fields = line.split('|')
    catalog.append({'id': key, 'area': area, 'label': label, 'audience': audience,
                    'approver': approver, 'fields': [{'key': name, 'label': FIELDS[name][0], 'kind': FIELDS[name][1]}
                                                  for name in fields.split(',')]})
assert len(catalog) == len({item['id'] for item in catalog})
encoded = json.dumps(catalog, ensure_ascii=False, separators=(',', ':'))
(ROOT / 'frontend/workflow-catalog.js').write_text('export const WORKFLOW_TYPES = ' + encoded + ';\n')
(ROOT / 'apps-script/WorkflowCatalog.gs').write_text('/* Generated by scripts/generate_catalog.py; edit catalog/workflow-source.tsv. */\nvar WORKFLOW_TYPES_ = ' + encoded + ';\n')
print(f'{len(catalog)} workflow definitions generated')
